version: '3.9'

services:
  postgres:
    image: postgres:13.1-alpine
    container_name: postgres
    restart: on-failure
    env_file:
      - ./env
    ports:
      - "5432"
    volumes:
      - pgdata:/var/lib/postgresql/data:rw

  nginx:
    build: ./nginx
    container_name: nginx
    restart: on-failure
    ports:
      - "80:80"
    volumes:
      - todo_task_data:/todo_task/static
      - ./log:/var/log/nginx
    depends_on:
      - todo_task

  todo_task:
    build: ./todo_task
    container_name: todo_task
    restart: on-failure
    command: sh -c "/todo_task/entrypoint.sh"
    volumes:
      - ./todo_task/:/todo_task/
      - todo_task_data:/todo_task/static
    ports:
      - "8000"
    env_file:
      - ./env
    depends_on:
      - postgres

volumes:
  pgdata:
    driver: local
  todo_task_data:
    driver: local
